### ISSUE TITLE
Allow MenuItem to be subclassed

### ISSUE THREAD

**Issue by georgema1982** [borgstrom/django-simple-menu#40] opened 2016-01-03 00:08 UTC
Right now it seems that there's no way to sublcass MenuItem as it will cause circular import. Any idea how to allow subclassing MenuItem?

**Comment by borgstrom** [comment] 2016-01-03 00:25
Interesting idea.  Can you explain the use case a little more.  How would you want to use a custom subclass?

**Comment by georgema1982** [comment] 2016-01-03 00:47
Imagine an app that needs access control. Usually we add access control on the view either using django's decorator, third party mixins like django-braces or any other kind of validation function we define on the view. If the view doesn't allow the current user to access it, the corresponding menu item shouldn't be displayed. I know MenuItem allows a callable check parameter to be passed in. But it's basically an access control logic on the menu level that duplicates that of view's. To me, it's not DRY enough.

The way I'm trying to subclass it is that I want to override check_check function. The logic is that if check callable isn't provided, I can infer the view from the url of the menu item. Then I can get access control data or logic from the view and the check callable can have a default behavior.

Another option is that the check callable should accept another parameter, aka url, besides request.

**Comment by borgstrom** [comment] 2016-01-12 20:26
Now that #42 has been merged there is no longer a `check_check` function.

I believe you should be able to do this simply by writing a custom check function that you provide to all of your menu items.  This check function will get the current request as it's first parameter, and then you can figure out the view from the request path and determine permissions based on that.

Would this approach not work for you?

**Comment by georgema1982** [comment] 2016-01-12 21:29
I'm afraid that request alone isn't enough because request only contains current url path. The check function might want to access the url defined on the menuitem that owns this check function. Let's say I have a menu item like:

    MenuItem('Test', reverse('test_url'), check = some_check_function_that_wants_to_know_url_defined_on_this_menu_item)

As the names of this dummy check function implies, it wants to know its owner MenuItem's url. Maybe my requirement is a little too specific to my own needs. But I imagine that other people might want to calculate some values based on the parameters passed in the menuitem construct and attached these values as attributes to the menuitem instance when it's processed and use these attributes to render some complicated layout in the template. Right now, check function only access current request. What if the check function wants to know other attributes of the menuitem?

To tackle this requirement, I think there are three solutions.

First is that MenuItem is allowed to subclassed so that developers can extend it to meet their own requirements.

The second one is that check function can accept the owner menuitem apart from request. Basically the check function definition would become:

    def check(request, menuitem):

Where the menuitem is the check function's owner menuitem.

The last one is that another callback function is allowed to passed to menuitem constructor and will be called after the default process function. This function will accept request and the owner menuitem and can change the menuitem's attribute as it likes.

**Comment by borgstrom** [comment] 2016-01-12 23:10
Checkout the commit e680f48f in the custom-checks branch I just pushed.

Is this something along the lines of what you were thinking?  You can now access `self.url` in your custom `check` function.

**Comment by georgema1982** [comment] 2016-01-12 23:21
I wonder how I can access self.url in check function after this change. The check function is on the MenuItem instance. Shall I subclass the MenuItem?

**Comment by borgstrom** [comment] 2016-01-12 23:26
Yes, see the test I added.  It defines a custom check function, which has access to all the attrs on that specific MenuItem.

**Comment by georgema1982** [comment] 2016-01-12 23:37
Nice. I wonder if the circular import issue has been resolved using subclassing inside a project. Because test case and real project are different. In real project, Menu is constructed in menus.py. Menu and MenuItem is defined in menu module. Subclass of MenuItem is defined in its own module. So when a menu is loaded in a real project, the template tag imports menu module which loads from That's a circular import.

**Comment by borgstrom** [comment] 2016-01-12 23:41
I would create a `utils.menus` namespace (or something similar) inside your django project.  Then in that namespace you can do something like:

    from menu import MenuItem

    class MyMenuItem(MenuItem):
        def check(self, request):
            # ... implementation of custom check logic ...

Now in each or your `menus.py` file you just do:

    from menu import Menu
    from utils.menus import MyMenuItem

And then build your menus using MyMenuItem instead of MenuItem.  There shouldn't be any circular imports.

**Comment by borgstrom** [comment] 2016-01-12 23:52
@georgema1982 Let me know if you have anything else to discuss on this issue, otherwise I'll create a PR for the changes in the custom-checks branch.

**Comment by georgema1982** [comment] 2016-01-12 23:59
I will try again to see if circular import exists.

**Comment by georgema1982** [comment] 2016-01-14 06:15
I tried and still got "cannot import name MenuItem" error. Form the stacktrace, I can see simple menu's menu module tries to load one app's menus module. This menus module tries to import MyMenuItem. The module defining MyMenuItem fails at the line of "from menu import MenuItem".

**Comment by borgstrom** [comment] 2016-01-14 17:45
Can you post the stack trace please.

**Comment by georgema1982** [comment] 2016-01-15 06:20
Traceback (most recent call last):
  File "/home/george/.virtualenvs/jfw2/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/home/george/.virtualenvs/jfw2/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/george/.virtualenvs/jfw2/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/george/.virtualenvs/jfw2/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/george/.virtualenvs/jfw2/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/george/.virtualenvs/jfw2/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/george/.virtualenvs/jfw2/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/george/.virtualenvs/jfw2/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/george/.virtualenvs/jfw2/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/george/.virtualenvs/jfw2/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/george/.virtualenvs/jfw2/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/george/.virtualenvs/jfw2/local/lib/python2.7/site-packages/menu/templatetags/menu.py", line 16, in render
    menus = Menu.process(context['request'])
  File "/home/george/.virtualenvs/jfw2/local/lib/python2.7/site-packages/menu/menu.py", line 92, in process
    c.load_menus()
  File "/home/george/.virtualenvs/jfw2/local/lib/python2.7/site-packages/menu/menu.py", line 68, in load_menus
    __import__(menu_module, fromlist=["menu", ])
  File "/home/george/git/jfwadmin/district/menus.py", line 2, in <module>
    from common.menus import MyMenuItem
  File "/home/george/git/jfwadmin/common/menus.py", line 1, in <module>
    from menu.menu import MenuItem
  File "/home/george/git/jfwadmin/common/menu.py", line 1, in <module>
ImportError: cannot import name MenuItem

There should be no stack trace because there's a try except block around loading menus module. But I temporarily commented out it so that the exception can blow.

**Comment by borgstrom** [comment] 2016-01-15 15:29
The problem is your file "/home/george/git/jfwadmin/common/menu.py" is taking the "menu" namespace, and it can't import from itself.  You need to rename that to "menus.py" and the import should work.

**Comment by borgstrom** [comment] 2016-01-15 15:37
After you rename to menus.py, then:

> from menu.menu import MenuItem

This should be just `from menu import MenuItem`

**Comment by georgema1982** [comment] 2016-01-16 06:32
Actually there's no such file as "/home/george/git/jfwadmin/common/menu.py". I don't know why it appears in the console. The last traceable error is:

    File "/home/george/git/jfwadmin/common/menus.py", line 1, in
    from menu.menu import MenuItem

**Comment by borgstrom** [comment] 2016-01-19 18:15
Do you have a `menu.pyc` file left over?  From the stacktrace it seems that there's simply a namespace collision.

**Comment by georgema1982** [comment] 2016-01-20 05:40
Ah, there's indeed a menu.pyc. Removed it and it works fine now.

**Comment by borgstrom** [comment] 2016-01-20 06:27
I've been bitten by that before :)

Closing this issue.

**Closed by borgstrom** 2016-01-20 06:27 UTC
